version: '3.8'

services:
  mariadb-master:
    image: "mariadb:${MARIADB_VERSION}"
    container_name: mariadb-master
    ports:
      - "13306:3306"
    environment:
      - "MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}"
      - "ALLOW_EMPTY_PASSWORD=no"
    volumes:
      - "./init/master:/docker-entrypoint-initdb.d"
      - "./conf/master:/etc/mysql/conf.d"
#      - "./data/master:/var/lib/mysql"
  mariadb-slave:
    image: "mariadb:${MARIADB_VERSION}"
    container_name: mariadb-slave
    ports:
      - "23306:3306"
    volumes:
      - "./init/slave:/docker-entrypoint-initdb.d"
      - "./conf/slave:/etc/mysql/conf.d"
#      - "./data/slave:/var/lib/mysql"
    environment:
      - "MARIADB_MASTER_ROOT_PASSWORD=${MARIADB_PASSWORD}"
      - "MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}"
      - "ALLOW_EMPTY_PASSWORD=no"
    depends_on:
      - mariadb-master
    links:
      - mariadb-master
  mariadb-slave2:
    image: "mariadb:${MARIADB_VERSION}"
    container_name: mariadb-slave2
    ports:
      - "33306:3306"
    volumes:
      - "./init/slave:/docker-entrypoint-initdb.d"
      - "./conf/slave2:/etc/mysql/conf.d"
#      - "./data/slave2:/var/lib/mysql"
    environment:
      - "MARIADB_MASTER_ROOT_PASSWORD=${MARIADB_PASSWORD}"
      - "MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}"
      - "ALLOW_EMPTY_PASSWORD=no"
    depends_on:
      - mariadb-master
    links:
      - mariadb-master