:hardbreaks:
= Docker Tip

== container 접속
docker exec -it <container> bash

== Docker 자동실행
=== docker 실행시 다음 옵션 추가
--restart unless-stopped

=== 이미 실행중인 컨테이너에 적용하기
docker update --restart unless-stopped mariadb

--restart option
no, on-failure, always, unless-stopped


== docker data 폴더 변경하기
docker info
systemctl stop docker.service
systemctl stop docker.socket
cp -R /var/lib/docker /DATA/docker
vi /lib/systemd/system/docker.service
ExecStart 에 -g 신규디렉토리 추가
ExecStart=/usr/bin/dockerd -g /DATA/docker -H fd:// --containerd=/run/containerd/containerd.sock

systemctl daemon-reload
systemctl start docker.service

== Volume Mount 확인하기
docker inspect -f "{{ .Mounts }}" container-name
----
➜  docker git:(master) ✗ docker inspect -f "{{ .Mounts }}" prometheus
[{bind  /Users/jihwankim/dev/docker/prometheus/data /etc/prometheus   true rprivate} {volume 0d12d2562032a3f06f344107e7bc64a58f04aac330bbd6378a8f1e82ba91d0c8 /var/lib/docker/volumes/0d12d2562032a3f06f344107e7bc64a58f04aac330bbd6378a8f1e82ba91d0c8/_data /prometheus local  true }]
----

== Container 를 Image 로 커밋하기
docker commit -m "메시지" 컨테이너명 이미지명:태그


== Volumes
docker volume ls
docker volume inspect pinpoint-docker_mysql_data
docker volume rm pinpoint-docker_mysql_data

